version: '3'

services:
  front-museo:
    image: front-museo:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GENERATE_SOURCEMAP=false
      - REACT_APP_CLIENTE_ID=984900675153-dq66acaafnia92pbsu3l89vp7h0hlk0p.apps.googleusercontent.com
      - REACT_APP_CLIENT_SECRET=[secreto-google]
      - REACT_APP_URL_BACK=https://ingsoftware.ucuenca.edu.ec/
      - REACT_APP_URL_PROCESS=https://ingsoftware.ucuenca.edu.ec/
      - REACT_APP_SECRET_KEY=[clave-cifrado]
    depends_on:
      - back-museo

  back-museo:
    image: back-museo:latest
    restart: unless-stopped
    ports:
      - "4000:8080"
    environment:
      - PORT=8080
      - CLIENT_SECRET=[secreto-google]
      - HOST_DB=base-museo
      - PORT_DB=5432
      - USER_DB=museo
      - PASSWORD_DB=[clave-museo]
      - DB=museo-db
      - LOCALHOST=http://167.99.44.172:80
      - URL_PROCESS=http://process-museo:5000/
      - DIALECT_DB=postgres
      - USER_MAIL=info.museodelasconceptas@gmail.com
      - CLIENT_ID_MAIL=903289633210-75s11tgo1gvqf6urm9a7j8dd8hmkh6ib.apps.googleusercontent.com
      - CLIENT_SECRET_MAIL=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
      - REFRESH_TOKEN_MAIL=[secreto-mail]
      - SECRET_KEY=[clave-cifrado]
      - DIR_LOGS=/app/logs/back.log
      - URL_CONFIRMATION=https://ingsoftware.ucuenca.edu.ec/museodelasconceptas/login-page?token=
    depends_on:
      - base-museo
    stdin_open: true
    tty: true
    volumes:
      - db-data:/var/lib/postgresql/data
      - /home/rchocho/logs:/app/logs

  process-museo:
    image: process-museo:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - HOST_DB_PROCESS=base-museo
      - PORT_DB_PROCESS=5432
      - DB_USER=museo
      - PASSWORD_DB_PROCESS=[clave-base]
      - DATABASE_DB_PROCESS=museo-db
      - OPEN_API_KEY=sk-proj-oT6HYBhLSXvgpqLAtopqT3BlbkFJke4s35Olpv4hz6bOIuNK
      - EMBEDDING_MODEL=text-embedding-ada-002
      - OPENAI_MODEL=gpt-3.5-turbo-instruct
      - LLAMA_MODEL=dell-research-harvard/lt-wikidata-comp-es
      - DIR_ARCHIVOS=archivos/
      - DIR_CARGA=carga.txt
      - ENTRENAR_AUTOMATICO=1
      - DIR_LOGS=/app/logs/process.log
    depends_on:
      - base-museo
    stdin_open: true
    tty: true
    volumes:
      - db-data:/var/lib/postgresql/data
      - /home/rchocho/logs:/app/logs


  base-museo:
    image: base-museo:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=[clave-base]
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
